run:
  deadline: 5m
  tests: true

linters:
  enable:
  - bodyclose
  - contextcheck
  - goheader
  - goimports
  - gosec
  - misspell
  - nestif
  - reassign
  - whitespace

linters-settings:
  gofmt:
    simplify: true

  goheader:
    template: |-
      Copyright {{ YEAR }} {{ AUTHOR }} authors. All rights reserved.
      Use of this source code is governed by a BSD-style
      license that can be found in the LICENSE file.
    values:
      const:
        AUTHOR: tsuru

  govet:
    check-shadowing: true
    enable:
    - fieldalignment
    - unreachable
